name: Test Lighthouse Check
on:
  workflow_dispatch:
    inputs:
      deployed_url:
        description: Deployed Environment Url
        default: https://www-dev.chewy.net/
        required: true

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: /tmp/artifacts
          urls: ${{ github.event.inputs.deployed_url }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
